### ISSUE TITLE
error with a complex illustration

### ISSUE THREAD

**Issue by Drawbussi** [davidAlgis/pyDot2Dot#5]
![Verre_Spring 2](https://github.com/user-attachments/assets/d1a10dce-982c-445b-9a9e-6d1e826d859c)
When I used this one, the path seems the right method so I choose this one because the contour goes in and out and creates a "double" line.
One I choose path,
I visualize it.
I ckecked the good epsilon for me and once I launch "process", it failed after the mention "multiple contours ETC."
I get this error box
[error.txt](https://github.com/user-attachments/files/17882314/error.txt)

and that in the dot_2_dot.exe:
"Find multiple contours. Processing only the largest one.
Loading the corrected image from C:/Users/Utilisateur/Downloads/Verre_Spring 2.png...
Processing image C:/Users/Utilisateur/Downloads/Verre_Spring 2.png using 'Path' method...
Find multiple contours. Processing only the largest one.
Drawing points and labels on the image...
Elapsed time for image processing: 4.13 seconds"

**Comment by Drawbussi** [comment]
Traceback (most recent call last):
  File "H:\AUDREY\NotesAudrey\ApplicationUtilsByDavid\pyDot2Dot\src\gui\main_gui.py", line 805, in process
    self.handle_multiple_contours(input_path, dots, labels)
  File "H:\AUDREY\NotesAudrey\ApplicationUtilsByDavid\pyDot2Dot\src\gui\main_gui.py", line 873, in handle_multiple_contours
    contours_window.window.attributes("-topmost", True)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 2051, in wm_attributes
    return self.tk.call(args)
           ^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bad window path name ".!toplevel51"

**Comment by davidAlgis** [comment]
Thank you for you issue, but I didn't reproduce it with your comments. So I close the issue.
